version: "3.7"

services: 
    db:
        image: postgres 
        container_name: csv_db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=csv
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: csv
        ports: 
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - db
        depends_on: 
            - db

volumes:
    pgdata:
        driver: local

        